language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: Wm8Kmlnwn2bOkKvE37nwLE0g0hKXF/IW0znPwYuNued9n9IeaOOboeIwAzNGi6vJ7YTMKHGzAwjqrpgoOotav8WewmBntwktB7AB7akSTi6f/+SMF+w/JfPmUmZWvIKpAf9PDZIGFstUYJ4navpORNKOlOroPlP9NGtmmYNE4gE=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: DhnJ14T6ZETwLNv3VdssKJfpUwWVCQUnCvLVSfk2V2Kx9Ytu291PwdjyNX3qTnZHyjiOaiTSmhpb4NsybZkm2cQVNQJlakoSCPT8oa3SWLow2u9cPbMNHjzV27r5K5dIApXczjZpYA6y826v80EwwbbUPj7w60KOFWCd5CTjdCs=
sudo: false
